os: linux
dist: xenial
language: java
services:
  - mysql
jdk:
  - openjdk8
cache:
  directories:
  - "$HOME/.CommandBox/artifacts/"
  - "$HOME/.CommandBox/server/"
env:
  jobs:
    - ENGINE=adobe@2018 COLDBOX_VERSION=stable
    - ENGINE=adobe@2016 COLDBOX_VERSION=stable
    - ENGINE=lucee@5 COLDBOX_VERSION=stable
jobs:
  include:
    - if: type = cron
      env:
        - ENGINE=adobe@2018 COLDBOX_VERSION=be
        - ENGINE=adobe@2016 COLDBOX_VERSION=be
        - ENGINE=lucee@5 COLDBOX_VERSION=be
        - ENGINE=lucee@be COLDBOX_VERSION=stable
        - ENGINE=lucee@be COLDBOX_VERSION=be
before_install:
  - curl -fsSl https://downloads.ortussolutions.com/debs/gpg | sudo apt-key add -
  - sudo echo "deb http://downloads.ortussolutions.com/debs/noarch /" | sudo tee -a /etc/apt/sources.list.d/commandbox.list
  - mysql -e 'CREATE DATABASE quick;'
install:
  - sudo apt-get update && sudo apt-get --assume-yes install commandbox
  - box install commandbox-cfconfig,commandbox-cfformat
  - box install
  - box install coldbox@${COLDBOX_VERSION} --force
before_script:
  - box server start cfengine=$ENGINE port=8500 debug=true
script:
  - box testbox run runner='http://127.0.0.1:8500/tests/runner.cfm' verbose=false
  - box run-script format:check
after_success:
  - box install commandbox-semantic-release
  - box config set endpoints.forgebox.APIToken=${FORGEBOX_TOKEN}
  - box semantic-release
notifications:
  email:
    if: type = cron
    on_failure: always
